apply plugin: "com.gradleup.shadow"

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    neoForge {
        convertAccessWideners(tasks.named("shadowJar", Jar), "healthindicators.accesswidener")
    }
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven { url "https://api.modrinth.com/maven" }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    // Architectury API. This is optional, and you can comment it out if you don't need it.
    api "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"
    api "maven.modrinth:yacl:${project.yacl_neoforge}"

    common(project(path: ':common')) { transitive false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionNeoForge')) { transitive false }
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    dependsOn jar
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    zip64 = true
}

assemble.dependsOn shadowJar

components.java {
    addVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {}
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
